### ISSUE TITLE
Generise for all uses

### ISSUE THREAD

**Issue by harrytwright** [harrytwright/cli-config#3]
As I would like to use this as my base for all the CLI based systems, be is a service, or a CLI itself, this needs to be generic but also customisable

Future may be depreciated for a fork of `npmcli/config` but for now, it needs work.

### TODO:

- [ ] Better options
  - [ ] Set the envMap there, or if a `env-prefix` is passed it will work like REACT_APP_X or npm_config_x
- [ ] Async loading and Sync loading
  - [ ] Load configuration files if needs be.
  - [ ] Create overloads for index so`Config.constructor` is never passed back ??
